### ISSUE TITLE
[BUG]The position of calendar icon is incorrect.

### ISSUE THREAD

**Issue by Yqzzxlj** [DLUT-SIE/TMSFTT-FE#180]
### Describe the bug
We found that the form for time is not start with calendar icon. @Time1ess 

### Screenshots
![2019-05-01 19-51-58屏幕截图](https://user-images.githubusercontent.com/43257534/57016254-b2d28980-6c4b-11e9-974d-2dc246c436e1.png)
![2019-05-01 19-52-22屏幕截图](https://user-images.githubusercontent.com/43257534/57016260-b8c86a80-6c4b-11e9-81b2-e7435720d786.png)
![2019-05-01 19-52-51屏幕截图](https://user-images.githubusercontent.com/43257534/57016261-bd8d1e80-6c4b-11e9-8a16-ff8097f9bd47.png)

**Comment by Time1ess** [comment]
It looks like our source for fonts files is out-dated, try to replace fonts files from a newer source.
