### ISSUE TITLE
[Feature Request]Add a list-view page for training records

### ISSUE THREAD

**Issue by Yqzzxlj** [DLUT-SIE/TMSFTT-FE#31]
### Please describe the problem you want to solve.
We need a page to allow admins and users view training records as a list.

### Describe the solution you'd like.
This page will display the training records in the form of a list.

### Additional context.
None.

**Comment by Time1ess** [comment]
As a reminder, regular users can only see records related to him/her (submitted by the user or submitted by admin, override the `get_queryset()` method of `viewset` would be way). BTW, admins can see records belongs to the department that he/she is in charge of, but we will talk about it later.

You can refer to https://github.com/DLUT-SIE/TMSFTT-BE/blob/302de544be59e310951499aaa5b137103a997076/infra/views.py#L18-L24 to see how it works.

**Comment by Time1ess** [comment]
Close as the PR has been merged.
